if ( NOT OX_PLATFORM )
	if ( CMAKE_SYSTEM_NAME MATCHES "Windows" )
		set( OX_PLATFORM "windows" )
	elseif ( CMAKE_SYSTEM_NAME MATCHES "Linux" )
		set( OX_PLATFORM "linux" )
	else ()
		message( FATAL_ERROR "Unable to detect target platform. Please manually specify UL_PLATFORM when running CMake." )
	endif ()
endif ()
